backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "assets/img/uploads" # Media files will be stored in the repo under this folder
public_folder: "/assets/img/uploads" # The folder where the files will be served from (URL path)

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the CMS UI
    folder: "_posts" # Path to the folder where the blog posts are stored
    create: true # Allow users to create new blog posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "DD-MM-YYYY",
        } # Update for date format
      - {
          label: "Categories",
          name: "categories",
          widget: "list",
          default: ["general"],
          allow_add: true,
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
